version: "3.8"

services:
  web:
    build: .
    image: genx:latest
    command: ["-web", "-port", "8080"]
    ports:
      - "8080"
    restart: unless-stopped

  preview:
    build: .
    image: genx:latest
    command: ["-web", "-port", "8081"]
    ports:
      - "8081:8081"
    restart: unless-stopped